# Generated by Django 3.1.7 on 2021-11-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211106_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='api_key',
            new_name='trendyol_api_key',
        ),
        migrations.AddField(
            model_name='user',
            name='woocommerce_api_key',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
