# Generated by Django 3.1.7 on 2021-11-07 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211107_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='woocommerce_api_secret',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='woocommerce_sitename',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=200)),
                ('shipping_address', models.CharField(max_length=200)),
                ('billing_address', models.CharField(max_length=1000)),
                ('fee_lines', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
