# Generated by Django 3.1.7 on 2021-11-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211107_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parasut_client_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='parasut_client_secret',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='parasut_firma_no',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='parasut_password',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='parasut_username',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='trendyol_api_key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='woocommerce_api_key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='woocommerce_api_secret',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='woocommerce_sitename',
            field=models.CharField(max_length=200),
        ),
    ]
