# Generated by Django 3.1.7 on 2021-11-07 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211107_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='fee_lines',
            new_name='line_items',
        ),
    ]
