# Generated by Django 3.1.7 on 2021-11-07 01:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211107_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='line_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
