# Generated by Django 3.1.7 on 2021-11-07 02:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211107_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='line_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_address',
            field=models.CharField(max_length=1000),
        ),
    ]
