# Generated by Django 3.1.7 on 2021-11-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211107_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='platform',
            field=models.CharField(default='Woocommerce', max_length=30),
            preserve_default=False,
        ),
    ]
