# Generated by Django 3.1.7 on 2021-11-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_orders_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='billing_city',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='billing_state',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='shipping_city',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='shipping_state',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='billing_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_address',
            field=models.CharField(max_length=200),
        ),
    ]
