# Generated by Django 3.1.7 on 2021-11-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211108_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping_address',
            field=models.CharField(max_length=1000),
        ),
    ]
