# Generated by Django 3.1.7 on 2021-11-08 11:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211108_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='billing_address',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='orders',
            name='line_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), size=None),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_address',
            field=models.CharField(max_length=2000),
        ),
    ]
