# Generated by Django 3.1.7 on 2021-11-09 16:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211108_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='line_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None),
        ),
    ]
