# Generated by Django 3.1.7 on 2021-12-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211109_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='name_surname',
            field=models.CharField(default='Tugay Cantaş', max_length=30),
            preserve_default=False,
        ),
    ]
