# Generated by Django 3.1.7 on 2021-12-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_orders_name_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Deneme', max_length=20),
            preserve_default=False,
        ),
    ]
