# Generated by Django 3.1.7 on 2021-12-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='takip_no',
            field=models.CharField(default='Yok', max_length=30),
            preserve_default=False,
        ),
    ]
