# Generated by Django 3.1.7 on 2022-02-03 01:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_orders_takip_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None),
        ),
    ]
